export const FONTS = {
    black: require('../assets/fonts/Poppins/Poppins-Black.ttf'),
    blackItalic: require('../assets/fonts/Poppins/Poppins-BlackItalic.ttf'),
    bold: require('../assets/fonts/Poppins/Poppins-Bold.ttf'),
    boldItalic: require('../assets/fonts/Poppins/Poppins-BoldItalic.ttf'),
    extraBold: require('../assets/fonts/Poppins/Poppins-ExtraBold.ttf'),
    extraBoldItalic: require('../assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf'),
    extraLight: require('../assets/fonts/Poppins/Poppins-ExtraLight.ttf'),
    extraLightItalic: require('../assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf'),
    italic: require('../assets/fonts/Poppins/Poppins-Italic.ttf'),
    light: require('../assets/fonts/Poppins/Poppins-Light.ttf'),
    lightItalic: require('../assets/fonts/Poppins/Poppins-LightItalic.ttf'),
    medium: require('../assets/fonts/Poppins/Poppins-Medium.ttf'),
    mediumItalic: require('../assets/fonts/Poppins/Poppins-MediumItalic.ttf'),
    regular: require('../assets/fonts/Poppins/Poppins-Regular.ttf'),
    semiBold: require('../assets/fonts/Poppins/Poppins-SemiBold.ttf'),
    semiBoldItalic: require('../assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf'),
    thin: require('../assets/fonts/Poppins/Poppins-Thin.ttf'),
    thinItalic: require('../assets/fonts/Poppins/Poppins-ThinItalic.ttf'),
    openSansRegular: require('../assets/fonts/Open_Sans/OpenSans-Regular.ttf'),
    openSansBold: require('../assets/fonts/Open_Sans/OpenSans-Bold.ttf'),
    openSansSemiBold: require('../assets/fonts/Open_Sans/OpenSans-SemiBold.ttf'),
    openSansMedium: require('../assets/fonts/Open_Sans/OpenSans-Medium.ttf'),
}